-- BD2 - S02 Triggers DML y Auditoria Basica
-- Script completo y listo para ejecutar (ver explicacion en
-- docs/bd2/sesiones/S02_Triggers_DML_Auditoria.md, seccion 3).
--
-- Requisito: haber ejecutado antes S01_01_esquemas.sql y S01_02_tablas.sql
-- (crea BOM_CATALOGO.PRODUCTOS, sobre la que este trigger se dispara).

-- ============================================================
-- 1) Tabla de auditoria
-- ============================================================
CREATE TABLE BOM_CATALOGO.PRODUCTO_AUDITORIA (
    ID_AUDITORIA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_PRODUCTO      NUMBER,
    ACCION           VARCHAR2(10) NOT NULL,
    PRECIO_ANTERIOR  NUMBER(10,2),
    PRECIO_NUEVO     NUMBER(10,2),
    STOCK_ANTERIOR   NUMBER(10),
    STOCK_NUEVO      NUMBER(10),
    FECHA_EVENTO     TIMESTAMP DEFAULT SYSTIMESTAMP,
    USUARIO_ORACLE   VARCHAR2(30) DEFAULT USER
);

-- ============================================================
-- 2) Trigger BEFORE UPDATE FOR EACH ROW: regla automatica de negocio
--    (rechaza un ajuste de precio mayor al 50% en una sola operacion)
-- ============================================================
CREATE OR REPLACE TRIGGER BOM_CATALOGO.TRG_PRODUCTO_PRECIO_BU
BEFORE UPDATE OF PRECIO ON BOM_CATALOGO.PRODUCTOS
FOR EACH ROW
BEGIN
    IF :NEW.PRECIO < (:OLD.PRECIO * 0.5) THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'El precio no puede bajar mas del 50% en un solo ajuste. Actual: ' || :OLD.PRECIO || ', propuesto: ' || :NEW.PRECIO
        );
    END IF;
END;
/

-- ============================================================
-- 3) Trigger AFTER INSERT/UPDATE/DELETE FOR EACH ROW: auditoria basica,
--    con :OLD y :NEW
-- ============================================================
CREATE OR REPLACE TRIGGER BOM_CATALOGO.TRG_PRODUCTO_AUDITORIA
AFTER INSERT OR UPDATE OR DELETE ON BOM_CATALOGO.PRODUCTOS
FOR EACH ROW
DECLARE
    v_accion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_accion := 'INSERT';
    ELSIF UPDATING THEN
        v_accion := 'UPDATE';
    ELSE
        v_accion := 'DELETE';
    END IF;

    INSERT INTO BOM_CATALOGO.PRODUCTO_AUDITORIA (
        ID_PRODUCTO, ACCION, PRECIO_ANTERIOR, PRECIO_NUEVO, STOCK_ANTERIOR, STOCK_NUEVO
    ) VALUES (
        COALESCE(:NEW.ID, :OLD.ID),
        v_accion,
        :OLD.PRECIO, :NEW.PRECIO,
        :OLD.STOCK, :NEW.STOCK
    );
END;
/
