-- BD2 - S04 Optimizacion de Consultas SQL
-- Script completo y listo para ejecutar (ver explicacion en
-- docs/bd2/sesiones/S04_Optimizacion_Consultas_SQL.md, seccion 3).
--
-- Requisito: haber ejecutado antes S01_01_esquemas.sql, S01_02_tablas.sql
-- y S01_03_plsql.sql (crea BOM_CATALOGO.PRODUCTOS, con al menos un
-- producto real cargado desde LP2 S1-S3).
--
-- Bloques que requieren una cuenta DBA: 1) y 3).
-- Bloques que requieren conexion como BOMERP_APP: 2), 4), 5) y 6).

-- ============================================================
-- 1) Esquema BOM_VENTAS y sus tablas (cuenta DBA)
-- ============================================================
CREATE USER BOM_VENTAS IDENTIFIED BY "123456" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO BOM_VENTAS;

-- Conectado como BOM_VENTAS:
CREATE TABLE BOM_VENTAS.VENTAS (
    ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FECHA   TIMESTAMP NOT NULL,
    ESTADO  VARCHAR2(20) NOT NULL,
    TOTAL   NUMBER(12,2) NOT NULL,
    CONSTRAINT CK_VENTA_TOTAL CHECK (TOTAL >= 0)
);

CREATE TABLE BOM_VENTAS.DETALLE_VENTAS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_VENTA         NUMBER NOT NULL,
    ID_PRODUCTO      NUMBER NOT NULL,
    NOMBRE_PRODUCTO  VARCHAR2(120) NOT NULL,
    PRECIO_UNITARIO  NUMBER(10,2) NOT NULL,
    CANTIDAD         NUMBER(10) NOT NULL,
    SUBTOTAL         NUMBER(12,2) NOT NULL,
    CONSTRAINT FK_DETALLE_VENTA FOREIGN KEY (ID_VENTA)
        REFERENCES BOM_VENTAS.VENTAS(ID),
    CONSTRAINT CK_DETALLE_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETALLE_SUBTOTAL CHECK (SUBTOTAL >= 0)
);

-- Nota: ID_PRODUCTO NO lleva FOREIGN KEY hacia BOM_CATALOGO.PRODUCTOS,
-- a proposito (ver guia, 2.2) - el mismo criterio de separacion por
-- esquema que LP2 aplica a nivel de modulo Java con @NamedInterface.

-- ============================================================
-- 2) Permisos de BOMERP_APP sobre BOM_VENTAS (cuenta DBA)
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_VENTAS.VENTAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_VENTAS.DETALLE_VENTAS TO BOMERP_APP;

-- ============================================================
-- 3) Volumen de prueba (conectado como BOMERP_APP)
--    Ajusta el rango de ID_PRODUCTO si tu BOM_CATALOGO.PRODUCTOS
--    tiene ids muy distintos - el bloque usa MOD para no depender
--    de un id fijo.
-- ============================================================
DECLARE
    v_id_venta      NUMBER;
    v_max_producto  NUMBER;
BEGIN
    SELECT MAX(ID) INTO v_max_producto FROM BOM_CATALOGO.PRODUCTOS;

    FOR i IN 1..500 LOOP
        INSERT INTO BOM_VENTAS.VENTAS (FECHA, ESTADO, TOTAL)
        VALUES (SYSTIMESTAMP - MOD(i, 90), 'REGISTRADA', 0)
        RETURNING ID INTO v_id_venta;

        FOR j IN 1..(MOD(i, 3) + 1) LOOP
            INSERT INTO BOM_VENTAS.DETALLE_VENTAS
                (ID_VENTA, ID_PRODUCTO, NOMBRE_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, SUBTOTAL)
            VALUES
                (v_id_venta, MOD(i + j, v_max_producto) + 1, 'Producto de prueba', 50.00, j,
                 50.00 * j);
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

-- Verificacion del volumen cargado:
SELECT COUNT(*) AS TOTAL_VENTAS FROM BOM_VENTAS.VENTAS;
SELECT COUNT(*) AS TOTAL_DETALLES FROM BOM_VENTAS.DETALLE_VENTAS;

-- ============================================================
-- 4) EXPLAIN PLAN antes de optimizar (conectado como BOMERP_APP)
--    Consulta representativa: reporte de ventas por producto,
--    ultimos 30 dias - con la funcion sobre FECHA que 2.5 senala
--    como mala practica, a proposito, para comparar despues.
-- ============================================================
EXPLAIN PLAN FOR
SELECT p.NOMBRE, SUM(d.CANTIDAD) AS TOTAL_UNIDADES, SUM(d.SUBTOTAL) AS TOTAL_VENDIDO
FROM BOM_VENTAS.DETALLE_VENTAS d
JOIN BOM_VENTAS.VENTAS v ON v.ID = d.ID_VENTA
JOIN BOM_CATALOGO.PRODUCTOS p ON p.ID = d.ID_PRODUCTO
WHERE TRUNC(SYSDATE) - TRUNC(v.FECHA) <= 30
GROUP BY p.NOMBRE
ORDER BY TOTAL_VENDIDO DESC;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- ============================================================
-- 5) DBMS_STATS: actualizar estadisticas (cuenta DBA)
--    Gathering stats sobre tablas de otro esquema requiere
--    privilegio elevado.
-- ============================================================
EXEC DBMS_STATS.GATHER_TABLE_STATS('BOM_VENTAS', 'VENTAS');
EXEC DBMS_STATS.GATHER_TABLE_STATS('BOM_VENTAS', 'DETALLE_VENTAS');
EXEC DBMS_STATS.GATHER_TABLE_STATS('BOM_CATALOGO', 'PRODUCTOS');

-- Repite el EXPLAIN PLAN, sin cambiar la consulta todavia -
-- el unico cambio hasta este punto son las estadisticas:
EXPLAIN PLAN FOR
SELECT p.NOMBRE, SUM(d.CANTIDAD) AS TOTAL_UNIDADES, SUM(d.SUBTOTAL) AS TOTAL_VENDIDO
FROM BOM_VENTAS.DETALLE_VENTAS d
JOIN BOM_VENTAS.VENTAS v ON v.ID = d.ID_VENTA
JOIN BOM_CATALOGO.PRODUCTOS p ON p.ID = d.ID_PRODUCTO
WHERE TRUNC(SYSDATE) - TRUNC(v.FECHA) <= 30
GROUP BY p.NOMBRE
ORDER BY TOTAL_VENDIDO DESC;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- ============================================================
-- 6) Consulta reescrita (buena practica SQL) y EXPLAIN PLAN final
--    (conectado como BOMERP_APP)
--    Mismo resultado que 4)/5) - "ultimos 30 dias" - pero sin
--    envolver la columna FECHA en una funcion.
-- ============================================================
SELECT p.NOMBRE, SUM(d.CANTIDAD) AS TOTAL_UNIDADES, SUM(d.SUBTOTAL) AS TOTAL_VENDIDO
FROM BOM_VENTAS.DETALLE_VENTAS d
JOIN BOM_VENTAS.VENTAS v ON v.ID = d.ID_VENTA
JOIN BOM_CATALOGO.PRODUCTOS p ON p.ID = d.ID_PRODUCTO
WHERE v.FECHA >= TRUNC(SYSDATE) - 30
GROUP BY p.NOMBRE
ORDER BY TOTAL_VENDIDO DESC;

-- Antes de seguir: confirma que esta version devuelve el mismo
-- numero de productos y los mismos totales que la de 4)/5).

EXPLAIN PLAN FOR
SELECT p.NOMBRE, SUM(d.CANTIDAD) AS TOTAL_UNIDADES, SUM(d.SUBTOTAL) AS TOTAL_VENDIDO
FROM BOM_VENTAS.DETALLE_VENTAS d
JOIN BOM_VENTAS.VENTAS v ON v.ID = d.ID_VENTA
JOIN BOM_CATALOGO.PRODUCTOS p ON p.ID = d.ID_PRODUCTO
WHERE v.FECHA >= TRUNC(SYSDATE) - 30
GROUP BY p.NOMBRE
ORDER BY TOTAL_VENDIDO DESC;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
