CREATE TABLESPACE ts_bomerp DATAFILE 'ts_bomerp01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1G;
AUDIT SELECT, INSERT, UPDATE ON venta BY ACCESS;
AUDIT INSERT, UPDATE ON detalle_venta BY ACCESS;
AUDIT SESSION BY app_erp;
